server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - AddRequestHeader=X-GATEWAY-INTERNAL, true
      routes:
        - id: auth-service
          uri: http://${AUTH_HOST:auth-service}:${AUTH_PORT:8081}
          predicates:
            - Path=/api/auth/**
        - id: order-service
          uri: http://${ORDER_HOST:order-service}:${ORDER_PORT:8082}
          predicates:
            - Path=/orders/**
        - id: restaurant-service
          uri: http://${RESTAURANT_HOST:restaurant-service}:${RESTAURANT_PORT:8084}
          predicates:
            - Path=/restaurant/**
        # - id: biker-service
        #   uri: http://${BIKER_HOST:biker-service}:${BIKER_PORT:8085}
        #   predicates:
        #     - Path=/biker/**
        # - id: router-service
        #   uri: http://${ROUTER_HOST:router-service}:${ROUTER_PORT:8086}
        #   predicates:
        #     - Path=/api/route/**
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://${AUTH_HOST:auth-service}:${AUTH_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.deliguy: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
