server:
  port: 8080

spring:
  application:
    name: api-service

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-GATEWAY-INTERNAL, true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081

logging:
  level:
    org.springframework.security: INFO
